### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by Ted377** [wickenico/crypto-ticker-widget.js#1]
1. IOTA (MIOTA) is missing 
2. BEST icon is missing

**Comment by wickenico** [comment]
New Version 2.0.1 online: 
1. Added special handling for IOTA/MIOTA. You have to fill the first parameter with "IOT".
2. For BEST is no icon available on http://cryptoicons.co, sorry.

**Comment by wickenico** [comment]
You could create a new issue to the repo of atomiclabs: https://github.com/spothq/cryptocurrency-icons/issues
