### ISSUE TITLE
Is there any way to enable Coinmarketcap?

### ISSUE THREAD

**Issue by iCarl** [wickenico/crypto-ticker-widget.js#2]
I'd like to view my HNT in this widget.
Is there any way to add support for coinmarketcap or another exchanges API that supports this?

**Comment by wickenico** [comment]
Hi, I will check this in the next days :)

**Comment by iCarl** [comment]
Any news on implementation?

**Comment by wickenico** [comment]
Sorry, I didn't find the time since now.

**Comment by wickenico** [comment]
Hi @iCarl, Coinmarketgap requires an apikeys. My Intention is to deliver a widget without the needing of any apikeys where the user has to generate one, sorry.

WE could make an widget for coinmarketgap with the key in a seperate code.
