### ISSUE TITLE
CRO - Error: Cannot parse response to an image

### ISSUE THREAD

**Issue by iFrosty-tech** [wickenico/crypto-ticker-widget.js#3]
CRO doesn't work

**Comment by wickenico** [comment]
Added special handling for CRO

**Comment by iFrosty-tech** [comment]
Thanks @wickenico  for listening to my issue, but I'm noticing it still doesn't work. In particular, it gives me the error: "Error: Cannot parse response to an image".
Carrying out various tests I seem to have understood that this error appears when you try to use the default image. Furthermore, the image for CROs is this: "_/gh/atomiclabs/cryptocurrency-icons@9ab8d6934b83a4aa8ae5e8711609a70ca0ab1b2b/128/white/mco.png_" with the old name MCO. I tried to replace the variable '_base_' but another error arises.

**Comment by wickenico** [comment]
I will check 👍🏻

**Comment by wickenico** [comment]
I will check it.

**Comment by wickenico** [comment]
@Frostbyte98 I don't get the error which you described, what are your parameters and how did you test ist? 
With the parameters change in code or in the widget settings?
